title: Bookstore Management API
description: An API designed for booksellers and book lovers
theme: just-the-docs

url: https://btbristow.github.io/bookstore-management-api/
baseurl: "/bookstore-management-api"
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
